/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{vue,js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        ocre: '#D1451E',
        coral: '#F0633C',
        coralClaro: '#FFDBD1',
        creme: '#FFFAF3',
        verdeEscuro: '#263A29',
        verdeMedio: '#3D6D4A',
        cinza: '#444444',
        cinzaClaro: '#EFEFEF',
        //!SECTION - TEMPLATE BUTTON COLORS
        primary: {
          main: '#4C4DDC',
          surface: '#F5F5FF',
          border: '#DFE0F3',
          hover: '#3334CC',
          pressed: '#24248F',
          focus: '#DBDBF8',
        },
        secondary: {
          main: '#FFD33C',
          surface: '#FFF6D8',
          border: '#FFF0BE',
          hover: '#FFC80A',
          pressed: '#D6A600',
          focus: '#FFF6D8',
        },
        success: {
          main: '#50CD89',
          surface: '#F2FFF8',
          border: '#C5EED8',
          hover: '#46B277',
          pressed: '#28593F',
          focus: '#DCF5E7',
        },
        error: {
          main: '#F14141',
          surface: '#FFF2F2',
          border: '#FAC0C0',
          hover: '#D93A3A',
          pressed: '#802A2A',
          focus: '#FCD9D9',
        },
        info: {
          main: '#7239EA',
          surface: '#F6F2FF',
          border: '#D0BDF8',
          hover: '#6633D1',
          pressed: '#3F2478',
          focus: '#E3D7FB',
        },
        neutral: {
          10: '#FFFFFF',
          20: '#F5F5F5',
          30: '#EDEDED',
          40: '#D6D6D6',
          50: '#C2C2C2',
          60: '#878787',
          70: '#606060',
          80: '#383838',
          90: '#403A3A',
          100: '#101010',
        },
      },
      fontFamily: {
        Inter: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        4: '4px',
        8: '8px',
        12: '12px',
        16: '16px',
        20: '20px',
        24: '24px',
        28: '28px',
        32: '32px',
      },
      fontSize: {
        paragraph: ['18px', { lineHeight: '150%' }],
        paragraphLarge: ['22px', { lineHeight: '150%' }],
        subtitle: ['26px', { lineHeight: '150%' }],
        subtitleLarge: ['31px', { lineHeight: '150%' }],
        headingSmall: ['37px', { lineHeight: '120%' }],
        heading: ['44px', { lineHeight: '120%' }],
        headingLarge: ['53.7px', { lineHeight: '120%' }],
        //SECTION - BUTTON TEMPLATE
        h1: ['64px', { lineHeight: '120%' }],
        h2: ['48px', { lineHeight: '120%' }],
        h3: ['40px', { lineHeight: '120%' }],
        h4: ['32px', { lineHeight: '120%' }],
        h5: ['24px', { lineHeight: '120%' }],
        h6: ['18px', { lineHeight: '120%' }],
        bodyLarge: ['16px', { lineHeight: '24px' }],
        bodyMedium: ['14px', { lineHeight: '20px' }],
        bodySmall: ['12px', { lineHeight: '16px' }],
      },
      fontWeight: {
        bold: '700',
        semiBold: '600',
        medium: '500',
        regular: '400',
      },
    },
  },
  plugins: [],
}
